# This is a basic workflow to help you get started with Actions

name: AWS Lambda

on:
  push:
    paths:
      - 'aws/accept-message/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set version
        id: set-version
        run: echo "::set-env PACKAGE_VERSION=2021.1.1.$GITHUB_RUN_NUMBER"
      
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
        with:
          version: latest
          
      - name: Pack and Push
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}  
        run: |
          octo pack --id=OctoSubscriber --format=Zip --version=${env:PACKAGE_VERSION} --basePath="aws/accept-message/"
          octo push --package=OctoSubscriber.${env:PACKAGE_VERSION}.zip --server=${env:OCTOPUS_URL} --apiKey=${env:OCTOPUS_API_KEY}
